# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *

class Ui_MainWindow(object):
    number_a = 0
    number_b = 0
    operation= ""
    result = 0
    numPosition = 0
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(749, 583)
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 400, 101, 91))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 400, 101, 91))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 290, 101, 91))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 290, 101, 91))
        self.pushButton_4.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(290, 400, 101, 91))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 30, 51, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(110, 30, 51, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(180, 30, 51, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(40, 90, 51, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(110, 90, 51, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(180, 90, 51, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(40, 150, 51, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(110, 150, 51, 41))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(180, 150, 51, 41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(110, 210, 51, 41))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(290, 290, 101, 91))
        self.pushButton_16.setObjectName("pushButton_16")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(440, 30, 256, 461))
        self.listWidget.setObjectName("listWidget")
        self.calculatorLine = QtWidgets.QListWidgetItem("0")
        self.listWidget.addItem(self.calculatorLine)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 749, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "-"))
        self.pushButton_2.setText(_translate("MainWindow", "/"))
        self.pushButton_3.setText(_translate("MainWindow", "*"))
        self.pushButton_4.setText(_translate("MainWindow", "+"))
        self.pushButton_5.setText(_translate("MainWindow", "Clear"))
        self.pushButton_6.setText(_translate("MainWindow", "1"))
        self.pushButton_7.setText(_translate("MainWindow", "2"))
        self.pushButton_8.setText(_translate("MainWindow", "3"))
        self.pushButton_9.setText(_translate("MainWindow", "4"))
        self.pushButton_10.setText(_translate("MainWindow", "5"))
        self.pushButton_11.setText(_translate("MainWindow", "6"))
        self.pushButton_12.setText(_translate("MainWindow", "7"))
        self.pushButton_13.setText(_translate("MainWindow", "8"))
        self.pushButton_14.setText(_translate("MainWindow", "9"))
        self.pushButton_15.setText(_translate("MainWindow", "0"))
        self.pushButton_16.setText(_translate("MainWindow", "="))

    def configureConnections(self):
        #QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), self.minus_click)
        self.pushButton.clicked.connect(self.minus_click)
        self.pushButton_2.clicked.connect(self.divide_click)
        self.pushButton_3.clicked.connect(self.multiply_click)
        self.pushButton_4.clicked.connect(self.plus_click)
        self.pushButton_5.clicked.connect(self.clear_click)
        self.pushButton_6.clicked.connect(self.num1_click)
        self.pushButton_7.clicked.connect(self.num2_click)
        self.pushButton_8.clicked.connect(self.num3_click)
        self.pushButton_9.clicked.connect(self.num4_click)
        self.pushButton_10.clicked.connect(self.num5_click)
        self.pushButton_11.clicked.connect(self.num6_click)
        self.pushButton_12.clicked.connect(self.num7_click)
        self.pushButton_13.clicked.connect(self.num8_click)
        self.pushButton_14.clicked.connect(self.num9_click)
        self.pushButton_15.clicked.connect(self.num0_click)
        self.pushButton_16.clicked.connect(self.equal_click)

    def plus_click(self):
        self.operation = "+"
        self.numPosition = 1
        #self.listWidget.addItem(self.operation)

    def minus_click(self):
        self.operation = "-"
        self.numPosition = 1
        #self.listWidget.addItem(self.operation)

    def multiply_click(self):
        self.operation = "*"
        self.numPosition = 1
        #self.listWidget.addItem(self.operation)

    def divide_click(self):
        self.operation = "/"
        self.numPosition = 1
        #self.listWidget.addItem(self.operation)

    def clear_click(self):
        self.listWidget.clear()
        self.numPosition = 0

    def num1_click(self):
        if not self.numPosition:
            self.number_a = 1
        else:
            self.number_b = 1

    def num2_click(self):
        if not self.numPosition:
            self.number_a = 2
        else:
            self.number_b = 2

    def num3_click(self):
        if not self.numPosition:
            self.number_a = 3
        else:
            self.number_b = 3

    def num4_click(self):
        if not self.numPosition:
            self.number_a = 4
        else:
            self.number_b = 4

    def num5_click(self):
        if not self.numPosition:
            self.number_a = 5
        else:
            self.number_b = 5

    def num6_click(self):
        if not self.numPosition:
            self.number_a = 6
        else:
            self.number_b = 6

    def num7_click(self):
        if not self.numPosition:
            self.number_a = 7
        else:
            self.number_b = 7

    def num8_click(self):
        if not self.numPosition:
            self.number_a = 8
        else:
            self.number_b = 8

    def num9_click(self):
        if not self.numPosition:
            self.number_a = 9
        else:
            self.number_b = 9

    def num0_click(self):
        if not self.numPosition:
            self.number_a = 0
        else:
            self.number_b = 0

    def equal_click(self):
        self.numPosition = 0
        self.__innerCalculation()
        itemResult = QtWidgets.QListWidgetItem(str(self.number_a) + " " + self.operation + " " + str(self.number_b) + " = "+ str(self.result))
        self.listWidget.addItem(itemResult)

    def __innerCalculation(self):
        if self.operation == "+":
            self.result = self.number_a + self.number_b
        elif self.operation == "-":
            self.result = self.number_a - self.number_b
        elif self.operation == "*":
            self.result = self.number_a * self.number_b
        elif self.operation == "/":
            if self.number_b == 0:
                self.result = "inf"
            else:
                self.result = self.number_a + self.number_b

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.configureConnections()
    sys.exit(app.exec_())
